### ISSUE TITLE
[2.2.0.2a] NullPointerException on mob spawn/attack

### ISSUE THREAD

**Issue by Demonly** [Mitchellbrine/DiseaseCraft-2.0#13]
`java.lang.NullPointerException: Ticking entity
    at mc.Mitchellbrine.diseaseCraft.event.ContractingEvents.attackEvent(ContractingEvents.java:72)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_154_ContractingEvents_attackEvent_LivingAttackEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:302)
    at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:850)
    at net.minecraft.entity.monster.EntityMob.func_70652_k(EntityMob.java:143)
    at net.minecraft.entity.monster.EntityZombie.func_70652_k(EntityZombie.java:340)
    at net.minecraft.entity.ai.EntityAIAttackOnCollide.func_75246_d(EntityAIAttackOnCollide.java:162)
    at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:103)
    at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:582)
    at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2066)
    at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:388)
    at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:36)
    at net.minecraft.entity.monster.EntityZombie.func_70636_d(EntityZombie.java:244)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1899)
    at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:213)
    at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:41)
    at net.minecraft.entity.monster.EntityZombie.func_70071_h_(EntityZombie.java:335)
    at net.minecraft.world.World.func_72866_a(World.java:2674)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:795)
    at net.minecraft.world.World.func_72870_g(World.java:2623)
    at net.minecraft.world.World.func_72939_s(World.java:2423)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:628)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
    at java.lang.Thread.run(Thread.java:745)`

**Comment by Mitchellbrine** [comment]
I need the full log (including the version number).  
So this is on the server-side, not the client side?

**Comment by Mitchellbrine** [comment]
I have a confirmed full report of this crash from someone else. This is a legitimate crash and I'm looking into it now.

**Comment by Demonly** [comment]
Hey,

Sorry long reply, kinda posted this and forgot it was here. Haha. xD

**Comment by Mitchellbrine** [comment]
This problem should be fixed in the next and latest update for 1.7.10 (once I upload it to CurseForge)
