### ISSUE TITLE
Singleplayer Crash

### ISSUE THREAD

**Issue by voidswrath** [Mitchellbrine/DiseaseCraft-2.0#14]
Not sure what is going on here but after adding disease craft on 1558 forge clicking on my world and loading it crashed my client

---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 2/17/16 2:13 PM
Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:101)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:101)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
    Connection: net.minecraft.network.NetworkManager@1aa416a
Stacktrace:
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_51, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 3729195472 bytes (3556 MB) / 6538395648 bytes (6235 MB) up to 6538395648 bytes (6235 MB)
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms3840m -Xmx6784m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 4, tcache: 0, allocated: 12, tallocated: 94
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 103 mods loaded, 103 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 
    UCHIJAAAA   Forge{10.13.4.1558} [Minecraft Forge](forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 
    UCHIJAAAA   CodeChickenCore{1.0.7.46} [CodeChicken Core](minecraft.jar) 
    UCHIJAAAA   DCModLoader{1.0} [DCModuleLoader](minecraft.jar) 
    UCHIJAAAA   ivtoolkit{IvToolkit} [1.2](minecraft.jar) 
    UCHIJAAAA   NotEnoughItems{1.0.5.111} [Not Enough Items](NotEnoughItems-1.7.10-1.0.5.111-universal.jar) 
    UCHIJAAAA   OpenModsCore{0.8} [OpenModsCore](minecraft.jar) 
    UCHIJAAAA   zeldaswordskills{1.7.10-2.3.1} [Zelda Sword Skills](1.7.10-zeldaswordskills-2.3.1.jar) 
    UCHIJAAAA   lucky{5.1.0} [Lucky Block]([1-7-10]_Lucky_Block_v5-1-0 %282%29.jar) 
    UCHIJAAAA   DamageIndicatorsMod{3.2.0} [Damage Indicators]([1.7.10]DamageIndicatorsMod-3.2.0.jar) 
    UCHIJAAAA   MetallurgyCore{4.0.4} [Metallurgy Core](MetallurgyCore-1.7.10-4.0.4.18.jar) 
    UCHIJAAAA   Agriculture{2.0} [Agriculture](Agriculture-1.7.10-2.0.52.jar) 
    UCHIJAAAA   armourersWorkshop{1.7.10-0.38.0.97} [Armourer's Workshop](Armourers-Workshop-1.7.10-0.38.0.97.jar) 
    UCHIJAAAA   plushieWrapper{0.0.0} [Plushie Wrapper](Armourers-Workshop-1.7.10-0.38.0.97.jar) 
    UCHIJAAAA   AtlanticCharacters{0.4.0} [Atlantic Characters](AtlanticCharacters-0.4.0.jar) 
    UCHIJAAAA   AtlantisWater{1.6.3} [Atlantian Water](AtlantisWater-1.6.3.jar) 
    UCHIJAAAA   babymobs{1.0} [Baby Mobs](BabyMobs-1.7.10-1.1 %281%29.jar) 
    UCHIJAAAA   BiblioCraft{1.11.4} [BiblioCraft](BiblioCraft[v1.11.4][MC1.7.10].jar) 
    UCHIJAAAA   Mantle{1.7.10-0.3.2.jenkins191} [Mantle](Mantle-1.7.10-0.3.2b.jar) 
    UCHIJAAAA   Natura{2.2.0} [Natura](natura-1.7.10-2.2.0.1 %281%29.jar) 
    UCHIJAAAA   Forestry{4.2.0.47} [Forestry for Minecraft](forestry_1.7.10-4.2.0.47.jar) 
    UCHIJAAAA   BiblioWoodsForestry{1.7} [BiblioWoods Forestry Edition](BiblioWoods[Forestry][v1.7].jar) 
    UCHIJAAAA   BiblioWoodsNatura{1.5} [BiblioWoods Natura Edition](BiblioWoods[Natura][v1.5].jar) 
    UCHIJAAAA   CameraStudio{2.1710} [Camera Studio](CameraStudioV2.1710%28mc1.7.10%29.zip) 
    UCHIJAAAA   CarpentersBlocks{3.3.6} [Carpenter's Blocks](Carpenter's Blocks v3.3.6 - MC 1.7.10.jar) 
    UCHIJAAAA   Railcraft{9.8.0.0} [Railcraft](Railcraft_1.7.10-9.8.0.0.jar) 
    UCHIJAAAA   ForgeMultipart{1.1.2.331} [Forge Multipart](ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
    UCHIJAAAA   chisel{2.5.1.44} [Chisel 2](Chisel2-2.5.1.44.jar) 
    UCHIJAAAA   craftingpillars{1.6.0} [Crafting Pillars Mod](CraftingPillars-1.7.x-1.6.1.jar) 
    UCHIJAAAA   CrossbowMod2{a0.1.6} [Crossbow Mod 2](Crossbow-Mod-2-1.7-0.2.14.jar) 
    UCHIJAAAA   CustomSpawner{3.3.0} [DrZhark's CustomSpawner](CustomMobSpawner 3.3.0.zip) 
    UCHIJAAAA   customnpcs{1.7.10d} [CustomNpcs](CustomNPCs_1.7.10d%284%29%281%29%281%29.jar) 
    UCHIJAAAA   PTRModelLib{1.0.0} [PTRModelLib](Decocraft-2.2.1a_1.7.10%281%29.jar) 
    UCHIJAAAA   props{2.2.1a} [Decocraft](Decocraft-2.2.1a_1.7.10%281%29.jar) 
    UCHIJAAAA   DiseaseCraft{2.0} [DiseaseCraft](DiseaseCraft-1.7.10-2.1.jar) 
    UCHIJAAAA   doggystyle{1.1.3.99} [Doggy Style](DoggyStyle-1.1.3.99.jar) 
    UCHIJAAAA   dungeonmobs{4.1.3} [Dungeon Mobs](Dungeon Mobs v4.1.3 %281%29.jar) 
    UCHIJAAAA   enhancedportals{3.0.12} [EnhancedPortals](EnhancedPortals_1.7.10-universal-3.0.12.jar) 
    UCHIJAAAA   fantastic{1.0.0} [Fantastic Fish](fantastic-1.4 %282%29.jar) 
    UCHIJAAAA   flansmod{4.10.0} [Flan's Mod](Flans Mod-1.7.10-4.10.0.jar) 
    UCHIJAAAA   FoodPlus{3.2rS} [§bFood Plus](FoodPlus-1.7.2-3.2rS.jar) 
    UCHIJAAAA   GardenContainers{1.7.10-1.7.0} [Garden Containers](GardenStuff-1.7.10-1.7.0.jar) 
    UCHIJAAAA   GardenCore{1.7.10-1.7.0} [Garden Core](GardenStuff-1.7.10-1.7.0.jar) 
    UCHIJAAAA   GardenStuff{1.7.10-1.7.0} [Garden Stuff](GardenStuff-1.7.10-1.7.0.jar) 
    UCHIJAAAA   GardenTrees{1.7.10-1.7.0} [Garden Trees](GardenStuff-1.7.10-1.7.0.jar) 
    UCHIJAAAA   grapplemod{1.7.10-v4} [grapplemod](grapplemod-v5-1.7.10.jar) 
    UCHIJAAAA   GrimoireOfGaia{1.0.0} [Grimoire of Gaia 3](GrimoireOfGaia3-1.7.10-1.2.7.jar) 
    UCHIJAAAA   hidenames{1.1.7} [Hide Names](Hide Names-1.7.10-1.1.8.jar) 
    UCHIJAAAA   iChunUtil{4.2.2} [iChunUtil](iChunUtil%282%29.jar) 
    UCHIJAAAA   malisiscore{1.7.10-0.13.1} [MalisisCore](malisiscore-1.7.10-0.13.1.jar) 
    UCHIJAAAA   malisisdoors{1.7.10-1.12.2} [Malisis' Doors](malisisdoors-1.7.10-1.12.2.jar) 
    UCHIJAAAA   Mekanism{8.1.7} [Mekanism](Mekanism-1.7.10-8.1.7.252.jar) 
    UCHIJAAAA   MekanismGenerators{8.1.7} [MekanismGenerators](MekanismGenerators-1.7.10-8.1.7.252.jar) 
    UCHIJAAAA   MekanismTools{8.1.7} [MekanismTools](MekanismTools-1.7.10-8.1.7.252.jar) 
    UCHIJAAAA   minepainter{0.2.6} [MinePainter](minepainter-0.2.6.jar) 
    UCHIJAAAA   thinknoodlesmod{1.0.12} [Thinknoodles mod](minions-1.7.10-1.0.12.jar) 
    UCHIJAAAA   modelcitizens{1.0.1} [Model Citizens](ModelCitizens-mc1.7.10-1.0.1.jar) 
    UCHIJAAAA   Morph{0.9.1} [Morph](Morph%282%29.jar) 
    UCHIJAAAA   cfm{3.4.8} [§9MrCrayfish's Furniture Mod](MrCrayfishFurnitureModv3.4.8%281.7.10%29.jar) 
    UCHIJAAAA   MSM3{3.0.0d} [More Swords 3](MSM-SNAP-3.0.0e-For-MC-1.7.10.jar) 
    UCHIJAAAA   NEIAddons{1.12.10.33} [NEI Addons](NEI Addons- Ex Nihilo.jar) 
    UCHIJAAAA   NEIAddons|AppEng{1.12.10.33} [NEI Addons: Applied Energistics 2](NEI Addons- Ex Nihilo.jar) 
    UCHIJAAAA   NEIAddons|Botany{1.12.10.33} [NEI Addons: Botany](NEI Addons- Ex Nihilo.jar) 
    UCHIJAAAA   NEIAddons|Forestry{1.12.10.33} [NEI Addons: Forestry](NEI Addons- Ex Nihilo.jar) 
    UCHIJAAAA   NEIAddons|CraftingTables{1.12.10.33} [NEI Addons: Crafting Tables](NEI Addons- Ex Nihilo.jar) 
    UCHIJAAAA   NEIAddons|ExNihilo{1.12.10.33} [NEI Addons: Ex Nihilo](NEI Addons- Ex Nihilo.jar) 
    UCHIJAAAA   OpenMods{0.8} [OpenMods](OpenModsLib-1.7.10-0.8.jar) 
    UCHIJAAAA   OpenBlocks{1.4.4} [OpenBlocks](OpenBlocks-1.7.10-1.4.4 %281%29.jar) 
    UCHIJAAAA   harvestcraft{1.7.10j} [Pam's HarvestCraft](Pam's HarvestCraft 1.7.10La %281%29.jar) 
    UCHIJAAAA   secretroomsmod{4.7.1} [The SecretRoomsMod](secretroomsmod-1.7.10-4.7.1.413.jar) 
    UCHIJAAAA   securitycraft{v1.6.1} [SecurityCraft](SecurityCraft v1.6.0 for 1.7.10.jar) 
    UCHIJAAAA   SSTOW{1.7.10-0.1-RC9-7} [Soul Shards: The Old Ways](Soul Shards- The Old Ways.jar) 
    UCHIJAAAA   sprinkles_for_vanilla{1.6.0} [sprinkles_for_vanilla](sprinklesforvanilla-1.7.10-1.6.0.jar) 
    UCHIJAAAA   stretchermod{1.0} [Stretcher Mod](StretcherMod-WaterFIx.jar) 
    UCHIJAAAA   TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct](TConstruct-1.7.10-1.8.8.jar) 
    UCHIJAAAA   weaponmod{v1.14.3} [Balkon's WeaponMod](weaponmod-1.14.3 %282%29.jar) 
    UCHIJAAAA   pixelartist{1.7.10-1.1.7} [pixelartist](XtraBlocks-1.7.10-1.1.7.jar) 
    UCHIJAAAA   xtrablocksbuildings{1.7.10-1.1.7} [xtrablocksbuildings](XtraBlocks-1.7.10-1.1.7.jar) 
    UCHIJAAAA   xtrablocksdiyadmin{1.7.10-1.1.7} [xtrablocksdiyadmin](XtraBlocks-1.7.10-1.1.7.jar) 
    UCHIJAAAA   xtrablocksdiycloth{1.7.10-1.1.7} [xtrablocksdiycloth](XtraBlocks-1.7.10-1.1.7.jar) 
    UCHIJAAAA   xtrablocksdiydecorations{1.7.10-1.1.7} [xtrablocksdiydecorations](XtraBlocks-1.7.10-1.1.7.jar) 
    UCHIJAAAA   xtrablocksdiydiscs{1.7.10-1.1.7} [xtrablocksdiydiscs](XtraBlocks-1.7.10-1.1.7.jar) 
    UCHIJAAAA   xtrablocksdiyfencing{1.7.10-1.1.7} [xtrablocksdiyfencing](XtraBlocks-1.7.10-1.1.7.jar) 
    UCHIJAAAA   xtrablocksdiyfood{1.7.10-1.1.7} [xtrablocksdiyfood](XtraBlocks-1.7.10-1.1.7.jar) 
    UCHIJAAAA   xtrablocksdiyglow{1.7.10-1.1.7} [xtrablocksdiyglow](XtraBlocks-1.7.10-1.1.7.jar) 
    UCHIJAAAA   xtrablocksdiyliquids{1.7.10-1.1.7} [xtrablocksdiyliquids](XtraBlocks-1.7.10-1.1.7.jar) 
    UCHIJAAAA   xtrablocksdiymetal{1.7.10-1.1.7} [xtrablocksdiymetal](XtraBlocks-1.7.10-1.1.7.jar) 
    UCHIJAAAA   xtrablocksdiypanels{1.7.10-1.1.7} [xtrablocksdiypanels](XtraBlocks-1.7.10-1.1.7.jar) 
    UCHIJAAAA   xtrablocksdiypowered{1.7.10-1.1.7} [xtrablocksdiypowered](XtraBlocks-1.7.10-1.1.7.jar) 
    UCHIJAAAA   xtrablocksdiysoundblocks{1.7.10-1.1.7} [xtrablocksdiysoundblocks](XtraBlocks-1.7.10-1.1.7.jar) 
    UCHIJAAAA   xtrablocksdiystone{1.7.10-1.1.7} [xtrablocksdiystone](XtraBlocks-1.7.10-1.1.7.jar) 
    UCHIJAAAA   xtrablocksdiystorage{1.7.10-1.1.7} [xtrablocksdiystorage](XtraBlocks-1.7.10-1.1.7.jar) 
    UCHIJAAAA   xtrablocksdiyweapons{1.7.10-1.1.7} [xtrablocksdiyweapons](XtraBlocks-1.7.10-1.1.7.jar) 
    UCHIJAAAA   xtrablocksdiywood{1.7.10-1.1.7} [xtrablocksdiywood](XtraBlocks-1.7.10-1.1.7.jar) 
    UCHIJAAAA   xtrablocksdiyxtras{1.7.10-1.1.7} [xtrablocksdiyxtras](XtraBlocks-1.7.10-1.1.7.jar) 
    UCHIJAAAA   xtrablocksdiyfurniture{1.7.10-1.1.7} [xtrablocksdiyfurniture](XtraBlocks-1.7.10-1.1.7.jar) 
    UCHIJAAAA   xtrablocksdiymiscmodels{1.7.10-1.1.7} [xtrablocksdiymiscmodels](XtraBlocks-1.7.10-1.1.7.jar) 
    UCHIJAAAA   xtrablocksdiytombs{1.7.10-1.1.7} [xtrablocksdiytombs](XtraBlocks-1.7.10-1.1.7.jar) 
    UCHIJAAAA   xtrablocksdiyglass{1.7.10-1.1.7} [xtrablocksdiyglass](XtraBlocks-1.7.10-1.1.7.jar) 
    UCHIJAAAA   yegamolchattels{1.1.2} [Ye Gamol Chattels](YeGamolChattels-1.1.2.jar) 
    UCHIJAAAA   McMultipart{1.1.2.331} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
    UCHIJAAAA   ForgeMicroblock{1.1.2.331} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
    Class transformer null safety: all safe
    Mantle Environment: Environment healthy.
    TConstruct Environment: Environment healthy.
    Stencil buffer state: Function set: GL30, pool: internal, bits: 8
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 1 / 8; [EntityPlayerMP['TheCodyMaverick'/2632, l='world', x=11.22, y=119.75, z=23.47]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by voidswrath** [comment]
Actually and update here I was using versions 2.1 for diseasecraft and when back to 2.0 and it loaded just fine

**Comment by Mitchellbrine** [comment]
Does this issue occur in the most recent version? It seems that something
was changed between 2.0 to 2.1 that broke it.

I'll look into it if it happens with the newest alpha, but that's
interesting. I'll check conflicts with new forge version and 2.1.

**Comment by Mitchellbrine** [comment]
When I put the newest version up (2.3) up, please confirm if this bug still exists.
