### ISSUE TITLE
NPE on Server during configregistry setup

### ISSUE THREAD

**Issue by Laikulo** [Mitchellbrine/DiseaseCraft-2.0#4]
Crash Report Follows

```
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 5/19/15 1:28 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
        at mc.Mitchellbrine.diseaseCraft.config.ConfigRegistry.init(ConfigRegistry.java:34)
        at mc.Mitchellbrine.diseaseCraft.DiseaseCraft.preInit(DiseaseCraft.java:65)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
        at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
        at com.google.common.eventbus.EventBus.post(EventBus.java:275)
        at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
        at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
        at com.google.common.eventbus.EventBus.post(EventBus.java:275)
        at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
        at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:533)
        at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88)
        at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
        Minecraft Version: 1.7.10
        Operating System: Linux (amd64) version 3.14.32-xxxx-grs-ipv6-64
        Java Version: 1.8.0_40, Oracle Corporation
        Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 357315672 bytes (340 MB) / 500170752 bytes (477 MB) up to 500170752 bytes (477 MB)
        JVM Flags: 2 total; -Xms512M -Xmx512M
        AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
        IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
        FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.3.1408 11 mods loaded, 11 mods active
        mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized
        FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.3.1408-1.7.10-universal.jar) Unloaded->Constructed->Pre-initialized
        Forge{10.13.3.1408} [Minecraft Forge] (forge-1.7.10-10.13.3.1408-1.7.10-universal.jar) Unloaded->Constructed->Pre-initialized
        jewelrycraft2{1.0.9} [Jewelrycraft 2] ([1.7.10] Jewelrycraft2-1.0.10-universal.jar) Unloaded->Constructed->Pre-initialized
        achget{1.0} [Achievement Get] (AchievementGet-1.7.10-1.0.1.jar) Unloaded->Constructed->Pre-initialized
        DiseaseCraft{2.0} [DiseaseCraft] (DiseaseCraft-1.7.10-2.0.jar) Unloaded->Constructed->Errored
        enderutilities{0.4.0} [Ender Utilities] (enderutilities-1.7.10-0.4.0.jar) Unloaded->Constructed->Pre-initialized
        hackery{0.2.1} [Hackery for Minecraft] (Hackery-0.2.1-jnks5-universal.jar) Unloaded->Constructed->Pre-initialized
        afm{1.0} [Arduino For Minecraft] (jamoojam-1.0.jar) Unloaded->Constructed->Pre-initialized
        examplemod{1.0} [Example Mod] (modid-1.0.jar) Unloaded->Constructed->Pre-initialized
        progressiveautomation{1.6.0} [Progressive Automation] (ProgressiveAutomation-1.7.10-1.6.0.jar) Unloaded->Constructed->Pre-initialized
        Profiler Position: N/A (disabled)
        Is Modded: Definitely; Server brand changed to 'fml,forge'
        Type: Dedicated Server (map_server.txt)
```

**Comment by Mitchellbrine** [comment]
This has to do with the module loader not running. Post the contents of the mod jar's META-INF file.

**Comment by Laikulo** [comment]
Manifest contains only

```
Manifest-Version: 1.0
```

The build.gradle also contains no manifest section

**Comment by Laikulo** [comment]
You'll want something like

```
jar{
    manifest{
        attributes(
            "key" : "value",
            "otherkey": "value"
       )
    }
}
```

**Comment by Mitchellbrine** [comment]
Damn. OH. Okay, this applies to the built version on the Jenkins. The version I've released contains the correct META-INF. Fixing right now.
