### ISSUE TITLE
My forge 1.7.10-10.13.3.1408 keeps crashing need help

### ISSUE THREAD

**Issue by PrimevalWerewolf** [Mitchellbrine/DiseaseCraft-2.0#6]
Every time I try to load a world it says 'Shuting down internal server' and crashes. Here's the crash report:
[20:08:39] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[20:08:39] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[20:08:39] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[20:08:39] [main/INFO] [FML]: Forge Mod Loader version 7.99.4.1408 for Minecraft 1.7.10 loading
[20:08:39] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Windows 8.1:amd64:6.3, installed at C:\Program Files (x86)\Minecraft\runtime\jre-x64\1.8.0_25
[20:08:39] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:08:39] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[20:08:39] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:08:39] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:08:39] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:08:43] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[20:08:43] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[20:08:43] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:08:43] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[20:08:44] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
[20:08:44] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
[20:08:44] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[20:08:46] [main/INFO]: Setting user: PrimevalWerewolf
[20:08:50] [Client thread/INFO]: LWJGL Version: 2.9.1
[20:08:51] [Client thread/INFO] [STDOUT]: [cpw.mods.fml.client.SplashProgress:start:180]: ---- Minecraft Crash Report ----
// You're mean.

Time: 5/26/15 8:08 PM
Description: Loading screen debug info

java.lang.Throwable
    at cpw.mods.fml.client.SplashProgress.start(SplashProgress.java:179)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:192)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 2894379632 bytes (2760 MB) / 3087007744 bytes (2944 MB) up to 3087007744 bytes (2944 MB)
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3072M -Xms3072M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: 
    GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.3355' Renderer: 'Intel(R) HD Graphics'
[20:08:52] [Client thread/INFO] [MinecraftForge]: Attempting early MinecraftForge initialization
[20:08:52] [Client thread/INFO] [FML]: MinecraftForge v10.13.3.1408 Initialized
[20:08:52] [Client thread/INFO] [FML]: Replaced 183 ore recipies
[20:08:52] [Client thread/INFO] [FML]: Preloading CrashReport classes
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.world.World$1
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.world.World$2
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.world.World$3
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.world.World$4
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.world.chunk.Chunk$1
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.crash.CrashReportCategory$1
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.crash.CrashReportCategory$2
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.crash.CrashReportCategory$3
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.entity.Entity$1
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.entity.Entity$2
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.entity.EntityTracker$1
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.world.gen.layer.GenLayer$1
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.world.gen.layer.GenLayer$2
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.entity.player.InventoryPlayer$1
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.world.gen.structure.MapGenStructure$1
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.world.gen.structure.MapGenStructure$2
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.world.gen.structure.MapGenStructure$3
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.server.MinecraftServer$3
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.server.MinecraftServer$4
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.server.MinecraftServer$5
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.nbt.NBTTagCompound$1
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.nbt.NBTTagCompound$2
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.network.NetHandlerPlayServer$2
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.network.NetworkSystem$3
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.tileentity.TileEntity$1
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.tileentity.TileEntity$2
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.tileentity.TileEntity$3
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.world.storage.WorldInfo$1
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.world.storage.WorldInfo$2
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.world.storage.WorldInfo$3
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.world.storage.WorldInfo$4
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.world.storage.WorldInfo$5
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.world.storage.WorldInfo$6
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.world.storage.WorldInfo$7
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.world.storage.WorldInfo$8
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.world.storage.WorldInfo$9
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.client.Minecraft$3
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.client.Minecraft$4
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.client.Minecraft$5
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.client.Minecraft$6
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.client.Minecraft$7
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.client.Minecraft$8
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.client.Minecraft$9
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.client.Minecraft$10
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.client.Minecraft$11
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.client.Minecraft$12
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.client.Minecraft$13
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.client.Minecraft$14
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.client.Minecraft$15
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.client.multiplayer.WorldClient$1
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.client.multiplayer.WorldClient$2
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.client.multiplayer.WorldClient$3
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.client.multiplayer.WorldClient$4
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.client.particle,EffectRenderer$1
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.client.particle,EffectRenderer$2
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.client.particle,EffectRenderer$3
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.client.particle,EffectRenderer$4
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.client.renderer.EntityRenderer$1
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.client.renderer.EntityRenderer$2
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.client.renderer.EntityRenderer$3
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.server.integrated.IntegratedServer$1
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.server.integrated.IntegratedServer$2
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.client.renderer.RenderGlobal$1
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.client.renderer.entity.RenderItem$1
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.client.renderer.entity.RenderItem$2
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.client.renderer.entity.RenderItem$3
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.client.renderer.entity.RenderItem$4
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.client.renderer.texture.TextureAtlasSprite$1
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.client.renderer.texture.TextureManager$1
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.client.renderer.texture.TextureMap$1
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.client.renderer.texture.TextureMap$2
[20:08:52] [Client thread/INFO] [FML]:  net.minecraft.client.renderer.texture.TextureMap$3
[20:08:52] [Client thread/INFO] [MinecraftForge]: Completed early MinecraftForge initialization
[20:08:52] [Client thread/INFO] [FML]: Found 0 mods from the command line. Injecting into mod discoverer
[20:08:52] [Client thread/INFO] [FML]: Searching C:\Users\Elora\AppData\Roaming.minecraft\mods for mods
[20:08:59] [Client thread/INFO] [FML]: Forge Mod Loader has identified 3 mods to load
[20:08:59] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge] at CLIENT
[20:08:59] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge] at SERVER
[20:09:00] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge
[20:09:00] [Client thread/INFO] [FML]: Processing ObjectHolder annotations
[20:09:00] [Client thread/INFO] [FML]: Found 341 ObjectHolder annotations
[20:09:00] [Client thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[20:09:00] [Client thread/INFO] [FML]: Applying holder lookups
[20:09:00] [Client thread/INFO] [FML]: Holder lookups applied
[20:09:00] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[20:09:00] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Starting up SoundSystem...
[20:09:01] [Thread-8/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Initializing LWJGL OpenAL
[20:09:01] [Thread-8/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]:     (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[20:09:01] [Thread-8/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: OpenAL initialized.
[20:09:01] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[20:09:01] [Sound Library Loader/INFO]: Sound engine started
[20:09:04] [Client thread/INFO]: Created: 512x256 textures/blocks-atlas
[20:09:04] [Client thread/INFO]: Created: 256x256 textures/items-atlas
[20:09:05] [Client thread/INFO] [FML]: Forge Mod Loader has successfully loaded 3 mods
[20:09:05] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge
[20:09:06] [Client thread/INFO]: Created: 512x256 textures/blocks-atlas
[20:09:06] [Client thread/INFO]: Created: 256x256 textures/items-atlas
[20:09:06] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[20:09:06] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: SoundSystem shutting down...
[20:09:06] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:importantMessage:90]:     Author: Paul Lamb, www.paulscode.com
[20:09:06] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[20:09:06] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[20:09:06] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Starting up SoundSystem...
[20:09:06] [Thread-10/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Initializing LWJGL OpenAL
[20:09:06] [Thread-10/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]:     (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[20:09:06] [Thread-10/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: OpenAL initialized.
[20:09:07] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[20:09:07] [Sound Library Loader/INFO]: Sound engine started
[20:09:08] [Client thread/ERROR]: Couldn't toggle fullscreen
java.lang.IllegalStateException: From thread Thread[Client thread,5,main]: Thread[Thread-6,5,main] already has the context current
    at org.lwjgl.opengl.ContextGL.checkAccess(ContextGL.java:184) ~[lwjgl-2.9.1.jar:?]
    at org.lwjgl.opengl.ContextGL.makeCurrent(ContextGL.java:189) ~[lwjgl-2.9.1.jar:?]
    at org.lwjgl.opengl.DrawableGL.makeCurrent(DrawableGL.java:110) ~[lwjgl-2.9.1.jar:?]
    at org.lwjgl.opengl.Display.makeCurrent(Display.java:706) ~[lwjgl-2.9.1.jar:?]
    at org.lwjgl.opengl.Display.makeCurrentAndSetSwapInterval(Display.java:1025) ~[lwjgl-2.9.1.jar:?]
    at org.lwjgl.opengl.Display.setDisplayMode(Display.java:251) ~[lwjgl-2.9.1.jar:?]
    at net.minecraft.client.Minecraft.func_110441_Q(Minecraft.java:699) ~[bao.class:?]
    at net.minecraft.client.Minecraft.func_71352_k(Minecraft.java:1490) [bao.class:?]
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:571) [bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
    at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
[20:09:27] [Server thread/INFO]: Starting integrated minecraft server version 1.7.10
[20:09:27] [Server thread/INFO]: Generating keypair
[20:09:27] [Server thread/INFO] [FML]: Injecting existing block and item data into this server instance
[20:09:27] [Server thread/INFO] [FML]: Applying holder lookups
[20:09:27] [Server thread/INFO] [FML]: Holder lookups applied
[20:09:27] [Server thread/INFO] [FML]: Loading dimension 0 (New World) (net.minecraft.server.integrated.IntegratedServer@427b3ac4)
[20:09:27] [Server thread/INFO] [FML]: Loading dimension 1 (New World) (net.minecraft.server.integrated.IntegratedServer@427b3ac4)
[20:09:28] [Server thread/INFO] [FML]: Loading dimension -1 (New World) (net.minecraft.server.integrated.IntegratedServer@427b3ac4)
[20:09:28] [Server thread/INFO]: Preparing start region for level 0
[20:09:29] [Server thread/INFO]: Preparing spawn area: 12%
[20:09:30] [Server thread/INFO]: Preparing spawn area: 53%
[20:09:31] [Server thread/INFO]: Preparing spawn area: 83%
[20:09:31] [Server thread/INFO]: Changing view distance to 24, from 10
[20:09:32] [Netty Client IO #0/INFO] [FML]: Server protocol version 2
[20:09:32] [Netty IO #1/INFO] [FML]: Client protocol version 2
[20:09:32] [Netty IO #1/INFO] [FML]: Client attempting to join with 3 mods : FML@7.10.99.99,Forge@10.13.3.1408,mcp@9.05
[20:09:32] [Netty IO #1/INFO] [FML]: Attempting connection with missing mods [] at CLIENT
[20:09:32] [Netty Client IO #0/INFO] [FML]: Attempting connection with missing mods [] at SERVER
[20:09:33] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
[20:09:33] [Client thread/INFO] [FML]: [Client thread] Client side modded connection established
[20:09:33] [Server thread/INFO]: PrimevalWerewolf[local:E:3c6dd927] logged in with entity id 322 at (35.5, 71.0, 258.5)
[20:09:33] [Server thread/INFO]: PrimevalWerewolf joined the game

**Comment by Mitchellbrine** [comment]
DiseaseCraft isn't even installed on the client. My mod can't crash your game if it's not on the client.

If that's the correct log, I'm going to have to close the issue. If not, please fix.

**Comment by Mitchellbrine** [comment]
Going to close, since I've received no word since marking pending. Please feel free to open with a better log if one exists.
